version: "3.8"

networks:
  platform_net:
    external: false
    name: "platform_net"

services:
  oltp-db:
    restart: always
    image: mysql:latest
    container_name: mysql
    privileged: true
    volumes:
      - ./env/mysql/init/:/docker-entrypoint-initdb.d/
      - ./env/mysql/conf/:/etc/mysql/conf.d/
      - ./env/mysql/logs:/logs
#      - ./env/mysql/data:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: 'data_platform'
      MYSQL_USER: 'platform'
      MYSQL_PASSWORD: 'de2022'
      MYSQL_ROOT_PASSWORD: 'de2022'
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - platform_net
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true

  flyway:
    image: flyway/flyway:9.1.3
    container_name: flyway
    privileged: true
    volumes:
      - ./env/flyway/sql:/flyway/sql
      - ./env/flyway/drivers:/flyway/drivers
    command:
      -user=platform
      -password=de2022
      -url=jdbc:mysql://oltp-db:3306
      -schemas=data_platform
      -connectRetries=60
      -baselineOnMigrate=true
      -sqlMigrationSuffixes=.sql migrate
    networks:
      - platform_net
    restart: on-failure
    depends_on:
      - oltp-db

