version: "3.9"

networks:
  platform_net:
    external: false
    name: "platform_net"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    privileged: true
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./env/postgres/init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - platform_net
    ports:
      - "5432:5432"
    expose:
      - "5432"
  airflow:
    image: gavinup/airflow:2.3.4
    depends_on:
      postgres:
        condition: service_started
    networks:
      - platform_net
    volumes:
      - ./env/airflow/dags:/root/airflow/dags
    ports:
      - "8080:8080"
    expose:
      - "8080"

  flyway:
    image: flyway/flyway:9.1.3
    container_name: flyway
    privileged: true
    volumes:
      - ./env/flyway/sql:/flyway/sql
      - ./env/flyway/drivers:/flyway/drivers
    command:
      -user=oltp
      -password=oltp
      -url=jdbc:postgresql://postgres:5432/oltp_db
      -schemas=oltp
      -connectRetries=60
      -baselineOnMigrate=true
      -sqlMigrationSuffixes=.sql migrate
    networks:
      - platform_net
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

  metabase:
    image: gavinup/metabase:1.41.4
    networks:
      - platform_net
    ports:
      - "3000:3000"
    expose:
      - "3000"

volumes:
  postgres-db-volume:

