#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

CREATE USER airflow WITH PASSWORD 'airflow';
CREATE DATABASE airflow;
CREATE SCHEMA airflow;
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;

CREATE USER oltp WITH PASSWORD 'oltp';
CREATE DATABASE oltp_db;
CREATE SCHEMA oltp;
GRANT ALL PRIVILEGES ON DATABASE oltp_db TO oltp;

CREATE USER olap WITH PASSWORD 'olap';
CREATE DATABASE olap_db;
CREATE SCHEMA ods;
CREATE SCHEMA dwd;
CREATE SCHEMA dws;
CREATE SCHEMA dwt;
CREATE SCHEMA ads;
GRANT ALL PRIVILEGES ON DATABASE olap_db TO olap;

EOSQL
